project_id = "hwlokusmhcuwzvwyhhlu"

[functions.analyze-skin]
verify_jwt = false

[functions.get-recommendations]
verify_jwt = true

[functions.skin-chat]
verify_jwt = true

[functions.voice-assistant]
verify_jwt = true
